site_name: ⏳ AutoFeat ⌛️
site_url: https://github.com/autonlab/AutoFeat.github.io

repo_url: https://github.com/autonlab/AutoFeat
repo_name: AutoFeat

site_description: Documentation for AutoFeat, a high-performant package for time-series featurization.
site_author: Dhruv Srikanth
copyright: null

remote_branch: main
remote_name: lab

docs_dir: docs
site_dir: site
use_directory_urls: true

nav: 
  - 'About': index.md

  - 'Getting Started':
    - 'Installation': 'getting_started/installation.md'
    - 'Introduction': 'getting_started/introduction.md'

  - 'Tutorials':
    - 'Tutorial Guide' : 'tutorials/tutorials.md'
    - 'Multi-Feature Extraction': 'tutorials/multi_feature_extraction.md'
  
  - 'Features':
    - 'Feature Extractors': 'api/features.md'
    - 'Preprocessors': 'api/preprocess/preprocess.md'

  - 'API Reference':
    - 'Reference Guide': 'api/api.md'

    - 'Core': 'api/core/core.md'

    - 'Common' :
      - 'Mean Transform' : 'api/common/mean_transform.md'
      - 'Max Transform' : 'api/common/max_transform.md'
      - 'Min Transform' : 'api/common/min_transform.md'
      - 'Median Transform' : 'api/common/median_transform.md'
      - 'Std Transform' : 'api/common/std_transform.md'
      - 'Var Transform' : 'api/common/var_transform.md'
      - 'Quantile Transform' : 'api/common/quantile_transform.md'
      - 'Range Transform' : 'api/common/range_transform.md'
      - 'N-Valid Transform' : 'api/common/n_valid_transform.md'
      - 'IQR Transform' : 'api/common/iqr_transform.md'
      - 'Skew Transform' : 'api/common/skewness_transform.md'
      - 'Kurtosis Transform' : 'api/common/kurtosis_transform.md'

      - 'Data Sparsity Transform' : 'api/common/data_sparsity_transform.md'
      - 'Data Density Transform' : 'api/common/data_density_transform.md'

      - 'Entropy Transform' : 'api/common/entropy_transform.md'
      - 'Cross Entropy Transform' : 'api/common/cross_entropy_transform.md'
      - 'Sample Entropy Transform' : 'api/common/sample_entropy_transform.md'

    - 'Functional' :
      - 'mean' : 'api/functional/mean.md'
      - 'max' : 'api/functional/max.md'
      - 'min' : 'api/functional/min.md'
      - 'median' : 'api/functional/median.md'
      - 'std' : 'api/functional/std.md'
      - 'var' : 'api/functional/var.md'
      - 'quantile' : 'api/functional/quantile.md'
      - 'range' : 'api/functional/range.md'
      - 'n-valid' : 'api/functional/n_valid.md'
      - 'iqr' : 'api/functional/iqr.md'
      - 'skewness' : 'api/functional/skewness.md'
      - 'kurtosis' : 'api/functional/kurtosis.md'

      - 'data sparsity' : 'api/functional/data_sparsity.md'
      - 'data density' : 'api/functional/data_density.md'

      - 'entropy' : 'api/functional/entropy.md'
      - 'cross entropy' : 'api/functional/cross_entropy.md'
      - 'sample entropy' : 'api/functional/sample_entropy.md'

    - 'Preprocess': 
      - 'Functional' :
        - 'delta' : 'api/preprocess/functional/delta_preprocessor_fn.md'
        - 'delta mean' : 'api/preprocess/functional/delta_mean_preprocessor_fn.md'
        - 'delta max' : 'api/preprocess/functional/delta_max_preprocessor_fn.md'
        - 'delta min' : 'api/preprocess/functional/delta_min_preprocessor_fn.md'
        - 'delta median' : 'api/preprocess/functional/delta_median_preprocessor_fn.md'
        - 'delta std' : 'api/preprocess/functional/delta_std_preprocessor_fn.md'
        - 'delta var' : 'api/preprocess/functional/delta_var_preprocessor_fn.md'
        - 'delta quantile' : 'api/preprocess/functional/delta_quantile_preprocessor_fn.md'

        - '1D DFT' : 'api/preprocess/functional/dft_preprocessor_fn.md'

      - 'Transform' : 
        - 'Delta Transform' : 'api/preprocess/transform/delta_preprocessor.md'
        - 'Delta Mean Transform' : 'api/preprocess/transform/delta_mean_preprocessor.md'
        - 'Delta Max Transform' : 'api/preprocess/transform/delta_max_preprocessor.md'
        - 'Delta Min Transform' : 'api/preprocess/transform/delta_min_preprocessor.md'
        - 'Delta Median Transform' : 'api/preprocess/transform/delta_median_preprocessor.md'
        - 'Delta Std Transform' : 'api/preprocess/transform/delta_std_preprocessor.md'
        - 'Delta Var Transform' : 'api/preprocess/transform/delta_var_preprocessor.md'
        - 'Delta Quantile Transform' : 'api/preprocess/transform/delta_quantile_preprocessor.md'

        - '1D DFT Transform' : 'api/preprocess/transform/dft_preprocessor.md'

    - 'Health' : 'api/health/health.md'

  - 'Community':
    - 'Contributing': 'community/contributing.md'

theme:
  name: material
  locale: en
  
  palette:
    primary: red
    accent: red
    
    # # Palette toggle for light mode
    # - scheme: default
    #   primary: red
    #   accent: red
    #   toggle:
    #     name: Dark Theme
    #     icon: material/brightness-7 

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: red
    #   accent: red
    #   toggle:
    #     name: Light Theme
    #     icon: material/brightness-4
  
  features:
    # - navigation.instant
    - navigation.collapse
    - navigation.top
    - navigation.footer
    - navigation.indexes
    # - navigation.tabs
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

    - content.code.copy
    - content.code.annotate

    - social

    - toc.follow
  
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  
  icon:
    repo: fontawesome/brands/github
  
  logo: assets/DS.svg
    
  include_homepage_in_sidebar: true
  highlightjs: true
  hijs_languages:
    - python

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      # enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths: [autofeat]
          options:
            show_source: false
            heading_level: 2

markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DhruvSrikanth
    - icon: fontawesome/brands/github
      link: https://github.com/DhruvSrikanth

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  # (1)!
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
