name: docs 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.6
      - name: Cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: pip install jinja2 \
                         markdown \
                         mkdocs \
                         mkdocs-material \
                         mkdocs-material-extensions \
                         pygments \
                         pymdown-extensions \
                         mkdocs-minify-plugin \
                         mkdocstrings \
                         'mkdocstrings[crystal,python]' \
                         colorama \
                         regex \
                         requests
      - name: Build
        run: git remote add lab "https://github.com/autonlab/AutoFeat.git"
      - name: Deploy
        run: mkdocs gh-deploy -c --force -t material
